{{ $values := .Values -}}
{{- range $projectName, $project := .Values.projects }}
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ $projectName }}
  namespace: tool-prod-axa-rev
  annotations:
    helm.sh/resource-policy: keep
    argocd.argoproj.io/sync-options: Prune=false
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  destinations:
    - name: '*'
      namespace: {{ $project.namespace | quote }}
      server: 'https://kubernetes.default.svc'
    - name: '*-applications'
      namespace: "tool-prod-axa-rev"
      server: 'https://kubernetes.default.svc'
  sourceRepos:
    - '*'
---
{{- end }}